apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: twistlock-console-template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    labels:
      name: console
    name: twistlock-console
  spec:
    host: {{ twistlock_external_route }}
    port:
      targetPort: mgmt-http
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: twistlock-console
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-11-14T15:00:37Z
        status: "True"
        type: Admitted
      host: {{ twistlock_external_route }}
      routerName: router
      wildcardPolicy: None
