apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: twistlock-defender-route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      name: console
    name: twistlock-defender
  spec:
    host: {{ twistlock_project_name }}-defender.apps.mgt.devsecops.gov
    port:
      targetPort: communication-port
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: passthrough
    to:
      kind: Service
      name: twistlock-console
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-12-03T22:08:48Z
        status: "True"
        type: Admitted
      host: {{ twistlock_project_name }}-defender.apps.mgt.devsecops.gov
      routerName: router
      wildcardPolicy: None
