apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: twistlock-service-sa
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: twistlock-service
